name: 刷步数

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  schedule:
    - cron: '5 0,2,5,7,9,11,13 * * *'
  watch:
    types: started
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: 开始
        run: |
          pip3 install requests
          user='${{ secrets.13461541865 }}'
          passwd='${{ secrets.13461541865WU }}'
          skey='${{ secrets.NO }}'
          sckey='${{ secrets.SCT22876Tx5MAevBwa3SEk0qKhZ8R103T }}'
          position='${{ secrets.false }}'
          corpid='${{ secrets.NO }}'
          corpsecret='${{ secrets.NO }}'
          agentid='${{ secrets.NO }}'
          touser='${{ secrets.NO }}'
          toparty='${{ secrets.NO }}'
          totag='${{ secrets.NO }}'
          open_get_weather='${{ secrets.False }}'
          area='${{ secrets.AREA }}'
          python3 main.py ${user} ${passwd} ${skey} ${sckey} ${position} ${corpid} ${corpsecret} ${agentid} ${touser} ${toparty} ${totag} ${open_get_weather} ${area}
